### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lint' of null

### ISSUE THREAD

**Issue by jackeller** [justinsthomas/combover#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [combover](https://github.com/justinsthomas/combover) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'lint' of null

```
At /Users/kellerj1/.atom/packages/combover/node_modules/csscomb/lib/core.js:44

TypeError: Cannot read property 'lint' of null
    at Comb.configure (/packages/combover/node_modules/csscomb/lib/core.js:44:23)
    at /packages/combover/node_modules/csscomb/lib/csscomb.js:29:10)
    at Object.comb (/packages/combover/lib/combover.js:75:22)
    at /packages/combover/lib/combover.js:34:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -5:04.6.0 combover:comb (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-csscomb 2.0.4 
atom-jinja2 0.6.0 
combover 0.1.0 
csscomb 0.3.1 
language-nunjucks 4.1.0 
postcss-sorting 2.10.0 
pretty-json 1.6.2 
```

**Comment by justinsthomas** [comment]
make sure you have a valid `.csscomb.json` file in the project root
